"""cambio en workspace

Revision ID: fb07a6b5ce0f
Revises: 5dfbd292a426
Create Date: 2022-01-31 13:56:56.839720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb07a6b5ce0f'
down_revision = '5dfbd292a426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
